### ISSUE TITLE
Moved issue: runBrowser: Can't search genes and can't load [simple bed]

### ISSUE THREAD

**Issue by joachimwolff** [deeptools/HiCBrowser#23]
Hello,

I have two problems with HiCBrowser and the runBrowser command.

- First, the gene search panel is not working, although the browserConfig.ini is pointing to a bed file working as intended as a [gene] track. The gene names are displayed in the browser, but when searching for the name of one of these genes, I get the following error:

`
Your search - FBtr0114187 - did not match any gene. Check the browser for examples of valid gene names as they may be an id.
`

While the `genes= file.bed ` in browserConfig.ini has that specific line:
`211000022278158	591	1036	FBtr0114187	0	+	1036	1036	0	1	445,	0,`

- Second, the loading of [simple bed] data is failing, as I have **Image Not Found** displayed in the browser, although the bed file is ok and the chromosome names are corresponding to the other files. Here's the example of a [simple bed] object that fails to load in the regions_tracks.ini:

```
[simple bed]
file = /home/richard/Claudia/HAS/dm6_genes.bed
title = HAS
color = black
# optional boder color. Set to none for no border color
#border_color = black
width = 10
# optional. If not given is guessed from the file ending
file_type = bed
```

Ask you me if you need the browserConfig.ini, region_tracks.ini and the corresponding bed files.

Ping @gtrichard I moved your issue because it was posted in the wrong repository.

Orginal posting: https://github.com/deeptools/HiCExplorer/issues/176

**Comment by bgruening** [comment]
@gtrichard which version are you using? Are you using the Docker container?

**Comment by gtrichard** [comment]
I am using the master branch with the commits from Dec 21, 2017.

**Comment by gtrichard** [comment]
I think that the error related to the bedfile that is not displayed might be related to this?

```
INFO:werkzeug:127.0.0.1 - - [09/Feb/2018 14:37:36] "GET /get_image?region=chr2R:1000000-11500000&id=13 HTTP/1.1" 200 -
[2018-02-09 14:37:36,341] ERROR in app: Exception on /get_image [GET]
Traceback (most recent call last):
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/hicbrowser/views.py", line 369, in get_image
    trp_list[img_id].plot(outfile, chromosome, start, end)
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 226, in plot
    track.plot(axis, label_axis, chrom, start, end)
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 1425, in plot
    self.process_bed(ax.get_figure().get_figwidth(), start_region, end_region)
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/hicexplorer/trackPlot.py", line 1351, in process_bed
    for bed in bed_file_h:
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/hicexplorer/readBed.py", line 105, in next
    bed = self.get_bed_interval(line)
  File "/data/akhtar/group/richard/Softwares/anaconda2/envs/hicexplorer_submatrices/lib/python2.7/site-packages/hicexplorer/readBed.py", line 250, in get_bed_interval
    return self.BedInterval._make(line_values)
  File "<string>", line 17, in _make
TypeError: Expected 6 arguments, got 4
```
